const mockQuestionBank = [
  "Describe the difference between a process and a thread in a software runtime. When would you choose one over the other?",
  "A production API endpoint is returning slow responses under load. Walk through how you would investigate and improve it.",
  "Design a simple chat system that supports many concurrent users. Explain your data model, API design, and scaling choices.",
  "Tell me about a time you had to explain a complex technical issue to a non-technical stakeholder. What was your approach?",
  "You need to add a feature that sends notifications to a large user base without blocking the main request path. How would you design it?",
];

const mockSessionStates = new Map();

function getSessionState(sessionId) {
  const key = sessionId || "default-mock-session";
  if (!mockSessionStates.has(key)) {
    mockSessionStates.set(key, {
      currentQuestion: 0,
      evaluations: [],
      completed: false,
    });
  }
  return mockSessionStates.get(key);
}

function buildEvaluation(questionNumber, answer) {
  const base = {
    score: 8,
    verdict: "STRONG",
    technicalAccuracy: 8,
    depth: 7,
    clarity: 8,
    feedback: "The answer showed solid fundamentals and practical reasoning.",
    strengths: ["Clear structure", "Practical trade-off explanation", "Good engineering judgement"],
    improvements: ["Add a bit more depth on edge cases", "Mention observability and failure handling"],
    summary: "This was a strong, demo-ready response for a development interview.",
    weaknesses: ["A couple of details could be expanded", "Could mention monitoring more explicitly"],
  };

  if (questionNumber === 2) {
    base.score = 7;
    base.verdict = "DEVELOPING";
    base.feedback = "The answer identified the right areas but would benefit from more concrete debugging steps.";
    base.strengths = ["Good problem-framing", "Reasonable first steps"];
    base.improvements = ["Add instrumentation and metrics", "Discuss bottleneck validation" ];
    base.summary = "The response was directionally correct and showed a good debugging mindset.";
    base.weaknesses = ["Missing specific measurement steps", "Need stronger prioritization"];
  }

  if (questionNumber === 4) {
    base.score = 9;
    base.verdict = "EXCELLENT";
    base.feedback = "The answer was thoughtful, well-structured, and tailored to the audience.";
    base.strengths = ["Excellent communication", "Clear stakeholder awareness", "Strong empathy"];
    base.improvements = ["Keep the same approach and add a bit more technical specificity"];
    base.summary = "This response was polished and demonstrated strong communication skills.";
    base.weaknesses = ["None major", "Could include a technical example for extra depth"];
  }

  if (answer && answer.length > 140) {
    base.score = Math.min(10, base.score + 1);
  }

  return base;
}

function buildOverallEvaluation() {
  return {
    overallScore: 8,
    verdict: "STRONG",
    technicalStrength: "The candidate demonstrated solid engineering judgment and clear communication across the interview.",
    technicalGaps: ["A few areas would benefit from deeper operational detail", "More explicit trade-off discussion around reliability"],
    strongestAreas: ["Structured reasoning", "Practical approach", "Communication"],
    areasToImprove: ["Operational depth", "Scalability trade-offs", "More concrete examples"],
    recommendation: "Strong candidate for a mid-level software engineering role with a good foundation for growth.",
    summary: "This is a convincing demo evaluation generated by the frontend mock API layer.",
  };
}

export function startInterview(payload) {
  const state = getSessionState(payload.sessionId);

  if (payload.answer) {
    state.answers = state.answers || [];
    state.answers.push(payload.answer);
  }

  if (state.currentQuestion >= mockQuestionBank.length) {
    state.completed = true;
    return {
      completed: true,
      questionNumber: state.currentQuestion,
      message: "Interview complete.",
      evaluationsReady: state.evaluations.length > 0,
    };
  }

  const question = mockQuestionBank[state.currentQuestion];
  const questionNumber = state.currentQuestion + 1;
  state.currentQuestion += 1;

  return {
    question,
    questionNumber,
  };
}

export function evaluate(payload) {
  const state = getSessionState(payload.sessionId);
  const questionNumber = payload.questionNumber || 1;
  const question = mockQuestionBank[Math.min(questionNumber - 1, mockQuestionBank.length - 1)];
  const evaluation = buildEvaluation(questionNumber, payload.answer);

  state.evaluations.push({
    questionNumber,
    question,
    answer: payload.answer,
    evaluation,
  });

  return evaluation;
}

export function evaluateOverall(payload) {
  const state = getSessionState(payload.sessionId);
  return buildOverallEvaluation(state.evaluations);
}

export function getResult(sessionId) {
  const state = getSessionState(sessionId);
  return {
    sessionId,
    completed: true,
    questionCount: mockQuestionBank.length,
    evaluations: state.evaluations.map((entry) => ({
      questionNumber: entry.questionNumber,
      question: entry.question,
      evaluation: entry.evaluation,
    })),
    overallEvaluation: buildOverallEvaluation(state.evaluations),
  };
}

export default {
  startInterview,
  evaluate,
  evaluateOverall,
  getResult,
};
